apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qx5y8g3n1-java-quarkus
  janus-idp.io/tekton: qx5y8g3n1-java-quarkus
  backstage.io/kubernetes-id: qx5y8g3n1-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qx5y8g3n1-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
